Data Cleaning

```{r setup}

#loading in packages
library(titanic)
library(dplyr)
library(janitor)
library(ggplot2)
library(tidyr)
library(Hmisc)
```

Link to Dataset: <https://www.kaggle.com/datasets/jainaru/global-ecological-footprint-2023>

-   The Kaggle view is very helpful and easy to read

```{r}

#loading in the dataset
fileName = list.files("data")
data <- read.csv(paste0("data/",fileName))

#looking at part of the data
head(data)
```

```{r}

#clean names
data <- clean_names(data, case="snake")


data <- rename(data, 
life_expectancy = life_exectancy, #spell expectancy correctly
sdgi = sd_gi, #get rid of the underscore
bu_land_footprint = built_up_land, #differentiate and shorthand the "built up lands"
bu_land_biocap = built_up_land_1, 
eco_difference = ecological_deficit_or_reserve, 
total_footprint = total_ecological_footprint_consumption, 
num_earth = number_of_earths_required, 
num_countries = number_of_countries_required)
#the last 4 just make them easier to work with


head(data)
```

No need to remove_empty since there are no entry points

```{r}

#dimensions of data
cat("The Dimensions are:",nrow(data), "x", ncol(data))
```

```{r}

#pandas .info()
str(data) #look at console
```

EDA on the footprint features

```{r}

#select the features ending with "footprint"
footprint_features <- select(data, "country", contains("footprint"))
print(footprint_features)
summary(footprint_features) #look at the console for this one
#total eco footprint is the sum of the other "footprints" and "build up land"
```

Countries vs. Their More Composite Features

```{r}
#country versus its total eco footprint
select(data, "country", "total_footprint")
```

```{r}

#country versus its eco difference
select(data, "country", "eco_difference")
```

```{r}

#HDI vs. eco difference
select(data, "country", "hdi", "eco_difference")
```

Making New Features

-   thanks Stephen for the idea of using the combo of eco deficit and num earth (idk if imma do this)

```{r}

#eco difference as a binary variable
featured_data <- mutate(data, is_sustainable = eco_difference>0)
select(featured_data, "country", "is_sustainable")

#a country with a positive eco_difference is sustainable because they used less resources than their country can provide

#plot the count of each
ggplot(featured_data, mapping = aes(x=is_sustainable)) + geom_bar() + labs(title = "Number of Sustainable Countries", x="Is Sustainable")
```
