Data Cleaning

```{r setup}

#loading in packages
library(titanic)
library(dplyr)
library(janitor)
library(ggplot2)
library(tidyr)
library(Hmisc)
```

Link to Dataset: <https://www.kaggle.com/datasets/jainaru/global-ecological-footprint-2023>

-   The Kaggle view is very helpful and easy to read

```{r}

#loading in the dataset
fileName = list.files("data")
data <- read.csv(paste0("data/",fileName))

#looking at part of the data
head(data)
```

```{r}

#clean names
data <- clean_names(data, case="snake")

#spelling expectancy right
data <- rename(data, life_expectancy = life_exectancy)

head(data)
```

No need to remove_empty since there are no entry points

```{r}

#dimensions of data
cat("The Dimensions are:",nrow(data), "x", ncol(data))
```

```{r}

#pandas .info()
str(data) #look at console
```

EDA on the footprint features

```{r}

#select the features ending with "footprint"
footprint_features <- select(data, "country", contains("footprint"))
print(footprint_features)
summary(footprint_features) #look at the console for this one

```

```{r}
#country versus it's total eco footprint
data <- rename(data, total_footprint = total_ecological_footprint_consumption)
select(data, "country", "total_footprint")
```
